name: Laravel Log Cleaner Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3' ]
        laravel: [ '9.*', '10.*', '11.*', '12.*' ]
        exclude:
          # Laravel 12 requires PHP 8.2+
          - php: '8.1'
            laravel: '12.*'


    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Create Laravel Project
        run: |
          composer create-project --prefer-dist laravel/laravel:${{ matrix.laravel }} test-app
          cd test-app
          composer require jiordiviera/laravel-log-cleaner

      - name: Generate Log Files
        run: |
          cd test-app
          php artisan tinker --execute="Log::info('Test log entry');"
          php artisan tinker --execute="Log::error('Test error entry');"

      - name: Run Log Cleaner
        run: |
          cd test-app
          php artisan log:clear

      - name: Check Log Files
        run: |
          cd test-app/storage/logs
          if [ -s laravel.log ]; then
            echo "Log file is not empty"
            exit 1
          else
            echo "Log file is empty or does not exist"
          fi

      - name: Run Package Tests
        run: vendor/bin/pest