name: Run Tests on Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2.5', '7.3', '7.4', '8.0', '8.1', '8.2']
        laravel-version: ['7.*', '8.*', '9.*', '10.*', '11.*']
        exclude:
          - php-version: '7.2.5'
            laravel-version: '9.*'
          - php-version: '7.2.5'
            laravel-version: '10.*'
          - php-version: '7.4'
            laravel-version: '9.*'
          - php-version: '7.4'
            laravel-version: '10.*'
          - php-version: '7.4'
            laravel-version: '11.*'
          - php-version: '8.0'
            laravel-version: '7.*'
          - php-version: '8.0'
            laravel-version: '11.*'

    name: PHP ${{ matrix.php-version }} - Laravel ${{ matrix.laravel-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, fileinfo
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel-version }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Show installed versions
        run: |
          php --version
          composer show laravel/framework

      - name: Run test suite
        run: vendor/bin/pest
