name: Run Tests on Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']
        laravel-versions: ['7.*', '8.*', '9.*', '10.*', '11.*']
        exclude:
          - php-versions: '7.4'
            laravel-versions: '7.*'
          - php-versions: '7.4'
            laravel-versions: '8.*'
          - php-versions: '7.4'
            laravel-versions: '10.*'
          - php-versions: '7.4'
            laravel-versions: '11.*'
          - php-versions: '8.0'
            laravel-versions: '11.*'
          - php-versions: '8.0'
            laravel-versions: '8.*'
          - php-versions: '8.0'
            laravel-versions: '10.*'
          - php-versions: '7.4'
            laravel-versions: '8.*'
          - php-versions: '7.4'
            laravel-versions: '9.*'
          - php-versions: '7.4'
            laravel-versions: '10.*'

    name: P${{ matrix.php-versions }} - L${{ matrix.laravel-versions }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel-versions }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Run test suite
        run: ./vendor/bin/pest
